### PR TITLE
Bakes schema objects after extensions baking

### LINKED ISSUE #292: Cannot resolve extended types
With the schema 
```
type Query {
    hello: String
}

extend type Query {
    world: String
}
```
I can see the extended fields in graphiql schema but as soon as i try to declare a resolver for the extended type like this
```
@Resolver('Query.world')
async def revolve_stuff(_, args, ctx, info):
    return 'hi'
```
baking the schema i get the error
```
Traceback (most recent call last):
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/schema/schema.py", line 348, in get_field_by_name
    return self.type_definitions[parent_name].find_field(field_name)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/types/object.py", line 125, in find_field
    return self.implemented_fields[name]
KeyError: 'world'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/morse/Documents/GitHub/play-tartiflette/src/__main__.py", line 54, in <module>
    run()
  File "/Users/morse/Documents/GitHub/play-tartiflette/src/__main__.py", line 52, in run
    web.run_app(app, port=8090,)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/web.py", line 415, in run_app
    reuse_port=reuse_port))
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/web.py", line 287, in _run_app
    await runner.setup()
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/web_runner.py", line 203, in setup
    self._server = await self._make_server()
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/web_runner.py", line 302, in _make_server
    await self._app.startup()
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette_aiohttp/__init__.py", line 97, in _cook_on_startup
    sdl=sdl, schema_name=schema_name, modules=modules
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/engine.py", line 250, in cook
    schema_name, custom_default_resolver, custom_default_type_resolver
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/schema/bakery.py", line 65, in bake
    schema = SchemaBakery._preheat(schema_name)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/schema/bakery.py", line 39, in _preheat
    obj.bake(schema)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/resolver/resolver.py", line 67, in bake
    field = schema.get_field_by_name(self.name)
  File "/Users/morse/.pyenv/versions/3.7.2/lib/python3.7/site-packages/tartiflette/schema/schema.py", line 351, in get_field_by_name
    f"field `{name}` was not found in GraphQL schema."
tartiflette.types.exceptions.tartiflette.UnknownSchemaFieldResolver: field `Query.world` was not found in GraphQL schema.
```
I am using the last published 1.0.0rc1 together with tartiflette-aiohttp==1.0.0

### PR DESCRIPTION
**Pull request by Maximilien-R**
Closes #292.

### CODE REVIEW

**Comment by abusi** [comment]
Looks good. Good catch and fix !

**Comment by abusi** [comment]
I completly missed the resolver definition case in the issue278, i tested default_resolver only.

**Comment by Maximilien-R** [comment]
I plead guilty too, I didn't see it while reviewing the #278 PR 😢 

Anyway, I bumped the package version to `1.0.0rc2` 😉

**Comment by abusi** [comment]
Perfect. I merge ;). We can don't care about sonar yet. It's not well configured

**Pull request merged**
