### PR TITLE
Provides flexibility on fields execution (sequentially/concurrently)

### PR DESCRIPTION
**Pull request by Maximilien-R**

### CODE REVIEW

**Comment by abusi** [comment]
Seems pretty cool to me @Maximilien-R 
Thanks again for your great work.

**Comment by abusi** [comment]
:heart: Looking very good

**Comment by aljinovic** [comment]
@abusi any ETA when this could be merged?

**Comment by abusi** [comment]
@Maximilien-R Is this ready or do you need more time ? @aljinovic seems to need it, so it may not be as "useless" as we thought.

**Comment by aljinovic** [comment]
I have a case when a lot of fields are resolved from memory, so async coroutines cause unnecessary CPU load for these resolvers. I patched this a while ago as I thought it might be a specific use case and was happy when I saw this MR.

**Pull request merged**
