### PR TITLE
ISSUE-134 - Support of Schema Directives.

### LINKED ISSUE #134: Schema and Operations directives
Directives on schema doesn't seems to be executed.

* **Tartiflette version:** 0.4.0
* **Python version:** 3.7.1
* **Executed in docker:** No
* **Is a regression from a previous versions?** No

SDL example:
```graphql
directive @non_introspectable on SCHEMA | FIELD_DEFINITION

type Query {
  aField: String
}

schema @nonIntrospectable {
  query: Query
}
```

Directive:
```python
import logging

from typing import Any, Callable, Dict

from tartiflette.directive import CommonDirective, Directive

logger = logging.getLogger(__name__)


@Directive("nonIntrospectable")
class NonIntrospectable(CommonDirective):
    @staticmethod
    def on_introspection(
        _directive_args: Dict[str, Any],
        _next_directive: Callable,
        _introspected_element: Any,
    ) -> None:
        logger.debug(">> NonIntrospectable.on_introspection")
        return None
```

When querying, the log is never triggered.

### PR DESCRIPTION
**Pull request by abusi**
Closes #134 

This is a work in progress.

### CODE REVIEW

**Comment by tsunammis** [comment]
@abusi Just a small remember. Could you keep in mind to remove the topic from the "known issues" list in the README?

**Comment by abusi** [comment]
@tsunammis Yep, thanks for the reminder :).

**Comment by tsunammis** [comment]
> @tsunammis Yep, thanks for the reminder :).

You're welcome

**Comment by remorses** [comment]
Can this be merged and deployed please?

**Comment by abusi** [comment]
@remorses Hi, thank you for your feedback. We are curently working on #121 with a complete rework of the paring and execution algorithm and query validation #262 (for example).
Then when this will be done we will move forward with schema and operation directive that will behave like middlewares. So for now, this PR won't move forward, I think I may close it anyway as the feature will be the same, but implemantation will change in the future.
Can you give me example of what you do with this unreleased feature so I can take it into account when reworking on this ?

**Comment by remorses** [comment]
I am using directives to make a sort of authorization mechanism.
An example of SDL
```graphql
directive @require(
    arg: String!
    equalTo: String!
    inside: LocationToCheck = OUTPUT
) on FIELD_DEFINITION

enum LocationToCheck {
    SESSION
    OUTPUT
}

type Query {
    something(id: ID): Something @require(arg: "id", equalTo: "byUserId", inside: OUTPUT)
}
```
The directive implementation (works for SESSION, `on_pre_output_coercion` isn't called)
```python
from typing import Any, Callable, Dict, Optional, NamedTuple
from tartiflette import Directive

class RequireInput(NamedTuple):
    arg: str
    equalTo: str
    inside: str

@Directive("require")
class Require:
    @staticmethod
    async def on_field_execution(
        directive_args: Dict[str, Any],
        next_resolver: Callable,
        parent_result: Optional[Any],
        args: Dict[str, Any],
        ctx: Optional[Dict[str, Any]],
        info: "Info",
    ) -> Any:
        directive_args = RequireInput(**directive_args)
        if directive_args.inside == 'SESSION':
            if not directive_args.arg in args:
                raise Exception(f'{directive_args.arg} not in args')
            if not getattr(ctx['req'], 'user', None):
                raise Exception(f'no session available')
            if args[directive_args.arg] != ctx['req'].user[directive_args.equalTo]:
                raise Exception(f'argument {args[directive_args.arg]} does not satisfy requirement {directive_args.arg} == {directive_args.equalTo}')
            else:
                return await next_resolver(parent_result, args, ctx, info)
        else:
            return await next_resolver(parent_result, args, ctx, info)

    @staticmethod
    async def on_pre_output_coercion(
        directive_args: Dict[str, Any],
        next_directive: Callable,
        value: Any,
        field_definition: "GraphQLField",
        ctx: Optional[Dict[str, Any]],
        info: "Info",
    ) -> Any:
        directive_args = RequireInput(**directive_args)
        args = field_definition.arguments
        print('value:', value)
        print('args:', args)
        if directive_args.inside == 'OUTPUT':
            if not directive_args.arg in args:
                raise Exception(f'{directive_args.arg} not in args')
            if not directive_args.equalTo in value:
                raise Exception(f'{directive_args.equalTo} not in OUTPUT')
            if args[directive_args.arg] != ctx['req'].user[directive_args.equalTo]:
                raise Exception(f'argument {args[directive_args.arg]} does not satisfy requirement {directive_args.arg} == {directive_args.equalTo}')
            else:
                return await next_directive(value, field_definition, ctx, info)
        else:
            return await next_directive(value, field_definition, ctx, info)

```

**Comment by abusi** [comment]
In your case `on_pre_output_coercion` is not called on your directive cause this handler is for directive location `SCALAR, ENUM, ENUM_VALUE, OBJECT`. your directive is a `FIELD_DEFINITION` ones and it expressed on a `field` not a type.

If you want to do something before the coercion a `Something` you need to do :
```
directive @requiere ........ on OBJECT

type something @require(....)
{

}
```

Now every field that will return a `Something` will have the `on_pre_output_coercion` hanlder of the `requiere` directived called before it's coercion.

>Note that your directive can do both. depending on were it will be expressed (Field_def or object) the correct handler will be called.

**Comment by remorses** [comment]
Thank you

**Comment by abusi** [comment]
Closed cause it'll be redone after 1.x is merged.

**Pull request closed without merging**
