### PR TITLE
ISSUE-381, find a way to call post_out on type when they are accessed via a Union.

### LINKED ISSUE #381: OBJECT supporting directive does not run if object is a part of union
* [ ] **Explain with a simple sentence the expected behavior**
I think the title covers the problem pretty much. The problem is easily reproducible.
I'm sorry, I can't provide the `Dockerfile` example. The image we're using is `python:3.8-alpine`, if that carries any weight.

Interestingly, placing the directive on the union definition will run the directive, despite the directive not supporting type UNION.

* [ ] **Tartiflette version:** _1.1.3_
* [ ] **Python version:** _3.8_
* [ ] **Executed in docker:** Yes
* [ ] **GraphQL Schema & Query:**
```
schema {
  query: Query
}

directive @run_me_this on OBJECT

type Query {
  rootQueryField: CoupleOfResponses
} 

union CoupleOfResponses = ResponseOne | ResponseTwo

type ResponseOne @run_me_this {
...
}


type ResponseTwo {
...
}
```

```
# code
class RunMeThis("run_me_this"):
  async def on_pre_output_coercion(self, directive_args, next_directive, value, ctx, info):
    # never runs
    return await next_directive(value, ctx, info)
```

```
# the request
query {
  rootQueryField {
    ...on ResponseOne {
      ...
    }
  }
}

### PR DESCRIPTION
**Pull request by abusi**
closes #381 

The idea is to calls the coercion of the runtimeType when union complete object is done. 
It does some reg, on 4 tests that I will investigate, but maybe @Maximilien-R you can already give me feedbacks on it, if you think its not to stupid.

Coercing the Union -> complete the object -> coerce_the_object (maybe it will call complete object to much :/) -> call the directive on the object. I don't know if I'm really clear on this @Maximilien-R ?

I'll continue to dive In.

### CODE REVIEW

**Comment by Maximilien-R** [comment]
Hi @abusi,

I digged into this issue a little bit. `abstract_coercer` & `object_coercer` do the same thing in the end (calling `complete_object_value`), calling the `output_coercer` of the `GraphQLObjectType` may be not the best solution. In our case this means we'll call two times `complete_object_value` (function which is in charge to collect & resolve children fields). Doing this could lead to overload and possible unexpected behaviors. For instance, if some of your children fields have directive you'll call them 2 times.

IMO, to properly handle this issue, we should first define what behavior we want for this case:
1. ```python
   complete_object_value(
       AbstractType.on_pre_output_coercion(
           ObjectType.on_pre_output_coercion(result)
       )
       *args,
   )
   ```
2. ```python
   complete_object_value(
       ObjectType.on_pre_output_coercion(
           AbstractType.on_pre_output_coercion(result)
       ),
       *args,
   )
   ```

To complie to the first behavior, the best solution (IMO) would be to store a `pre_output_coercion_directives` property at bake time for each `GraphQLObjectType` instances. This way, we'll be able to call them on the `abstract_coercer` function to only apply the directives and don't call `complete_object_value` multiple times:
```patch
--- a/tartiflette/types/object.py
+++ b/tartiflette/types/object.py
@@ -145,6 +145,11 @@ class GraphQLObjectType(GraphQLCompositeType, GraphQLType):
             directives_definition=directives_definition,
             directive_hook="on_introspection",
         )
+        self.pre_output_coercion_directives = wraps_with_directives(
+            directives_definition=directives_definition,
+            directive_hook="on_pre_output_coercion",
+            with_default=True,
+        )


--- a/tartiflette/coercers/outputs/abstract_coercer.py
+++ b/tartiflette/coercers/outputs/abstract_coercer.py
@@ -106,10 +106,16 @@ async def abstract_coercer(
         result,
     )
 
-    result = await complete_object_value(
-        result, info, execution_context, field_nodes, path, runtime_type
-    )
-
-    return await runtime_type.output_coercer(
-        result, info, execution_context, field_nodes, path
+    return await complete_object_value(
+        await runtime_type.pre_output_coercion_directives(
+            result,
+            execution_context.context,
+            info,
+            context_coercer=execution_context.context,
+        ),
+        info,
+        execution_context,
+        field_nodes,
+        path,
+        runtime_type,
```

Regarding the second behavior, I don't have an "easy" solution in mind, if this is the behavior we want, I can think of it and come back to you if I found a trick.

> Note: could you add a directive on the `Union` itself and on the `a` field? Also, having a case testing an `Interface` could be awesome. This way we should have a functional test covering all cases of `on_pre_output_coercion` for all abstact types and their children.

**Comment by abusi** [comment]
> I digged into this issue a little bit. `abstract_coercer` & `object_coercer` do the same thing in the end (calling `complete_object_value`), calling the `output_coercer` of the `GraphQLObjectType` may be not the best solution. In our case this means we'll call two times `complete_object_value` (function which is in charge to collect & resolve children fields). Doing this could lead to overload and possible unexpected behaviors. For instance, if some of your children fields have directives you'll call them 2 times.

Yep exactly what I saw, that why I was not convinced by my implementation. Thanks for confirming my suspicions. ❤️ 

What I want to achieve is to have the result to be coerced by the `abstract (Union/Iface)`, then having the `post_coerce` directive from `runtime_type` to be called then the `post_coerce` directive of the `abstract (Union/Iface)` to be called. A little like if the `abstract` was a wrapping type of the `runtime_type`

As you said, I think we need to prepare the directive without the target coercer, so we could run them independently, I'll try to think of something, so it won't add too much workload, I don't want to call `wrap_directive` too much inside the request execution path.

Thanks again @Maximilien-R.

**Comment by Maximilien-R** [comment]
Don't know if I wasn't clear or if I misunderstood your message so I prefer to clarify my point 😆 

The hook is `pre_output_coercion`, (not `post`) meaning we should apply directives before going deeper in the `abstract_coercer` (I mean call `complete_object_value`).

With my proposal, we would have the following behavior:
1. Resolving the abstract field through `GraphQLField.resolver`
2. In our case, this will call `complete_value_catching_error` which will call `GraphQLUnion.output_coercer`

The way it's implemented, all `output_coercer` are based on the [`output_directives_coercer`](https://github.com/tartiflette/tartiflette/blob/master/tartiflette/coercers/outputs/directives_coercer.py#L6) which will apply directives to compute the result to forward to the actual coercer (here [`abstract_coercer`](https://github.com/tartiflette/tartiflette/blob/master/tartiflette/coercers/outputs/abstract_coercer.py#L69)).

That's why I suggested to call the `GraphQLObject.pre_output_coercion_directives` on `abstract_coercer` just before calling `complete_object_value`.

This way, we'll apply the directives from the `GraphQLUnion` first, on which we'll apply the directives from the `GraphQLObject` before forwarding the result to the `complete_object_value`.

Since we define `GraphQLObject.pre_output_coercion_directives` at bake time there no issue related to call `wraps_with_directives` at execution time.

**Comment by abusi** [comment]
> Don't know if I wasn't clear or if I misunderstood your message so I prefer to clarify my point 😆
> 

Purrrrrfect, as usual.

> The hook is `pre_output_coercion`, (not `post`) meaning we should apply directives before going deeper in the `abstract_coercer` (I mean call `complete_object_value`).
> 

I always misread them preoutput/postinput. We're in agreement on this point.

> With my proposal, we would have the following behavior:
> 
> 1. Resolving the abstract field through `GraphQLField.resolver`
> 2. In our case, this will call `complete_value_catching_error` which will call `GraphQLUnion.output_coercer`
> 

Yep, Stellar, 👌 

> The way it's implemented, all `output_coercer` are based on the [`output_directives_coercer`](https://github.com/tartiflette/tartiflette/blob/master/tartiflette/coercers/outputs/directives_coercer.py#L6) which will apply directives to compute the result to forward to the actual coercer (here [`abstract_coercer`](https://github.com/tartiflette/tartiflette/blob/master/tartiflette/coercers/outputs/abstract_coercer.py#L69)).
> 
> That's why I suggested to call the `GraphQLObject.pre_output_coercion_directives` on `abstract_coercer` just before calling `complete_object_value`.
> 
> This way, we'll apply the directives from the `GraphQLUnion` first, on which we'll apply the directives from the `GraphQLObject` before forwarding the result to the `complete_object_value`.
> 
> Since we define `GraphQLObject.pre_output_coercion_directives` at bake time there no issue related to call `wraps_with_directives` at execution time.

Let's do this :)

**Comment by abusi** [comment]
@Maximilien-R I've done what you've been suggesting, it seems to work, I'll add more test cases in the anti-reg test to see if we also cover interface directive + type directive and the order they are called upon. Thanks for the help. :heart:

**Pull request merged**
