### PR TITLE
[v1.0.0rc1] Release of v1 feature set

### LINKED ISSUE #121: Improve query parsing and validation
It might be interesting to change the way queries are parsed and validated.

Currently we use the `libgraphqlparser` to browse the nodes of the query using callback functions that are called each time the parser encounters a new node in the document. At each node encountered the callback function generates a `VisitorElement` object which is then passed when calling the `update` method of the `Visitor` instance which is responsible of business logic (validation, addition of information to the visitor context, creation of `Node` object...).

These different processes are complex and long to execute. The addition of the management of new errors gradually make the code less and less readable and more difficult to maintain.

To tackle this problem, we could dissociate this unique treatment into separate steps:
1. Parse the query to generate a `DocumentNode` object containing all the information related to the query.
This step can be easily done by calling the `graphql_ast_to_json` `libgraphqlparser` function which analyzes the query and returns a string in `JSON` format containing all the information related to the query. This string could then be computed into a `DocumentNode` object.
2. Apply the set of validation rules defined by the GraphQL specification to this `DocumentNode` object.

Proceed in this way to several advantages:
1. Allow to cache for each query the generation of the `DocumentNode` and the application of validation rules.
2. Delete a lot of code (`Visitor`,` VisitorContext` & most of the code contained in `cffi` parser) and gain in simplicity/readability/maintainability.
3. Have a `DocumentNode` object conforming to the `GraphQL` [language specifications](https://facebook.github.io/graphql/June2018/#sec-Language). This would allow to be more faithful to the specifications but also to facilitate the on-boarding of new collaborators.
4. Be closer to the specification and allow to deal with some particular case still poorly managed currently (such as the merge of `SelectionSet`).

# TODO
- [x] Implements functions which parse a SDL or query string to a `DocumentNode` instance
- [x] Cache SDL/query parsing & validation
- [x] Use `DocumentNode` to build schema
- [x] Use `DocumentNode` to execute query

### LINKED ISSUE #122: Improve type resolving
Since `tartiflette` allow us to deal only with `dict`. Resolving the `__typename` field for an `UnionType` is difficult and is delegate to the `Resolver` implementation which need to return the `__typename` in the resolved value.

Maybe we could add an optional `resolve_type` argument to the `Resolver` decorator which could take a callable in charge of determining the `__typename` to return for the resolved value? This `resolve_type` parameter could be required for an `UnionType` resolver which returns a value where the `__typename` couldn't be resolved by the default `resolve_type` function (a `dict` without a `__typename` key for instance).

```python
@Resolver(
    "Query.catOrDog",
    resolve_type=lambda result: "Dog" if is_dog(result) else "Cat",
)
def query_cat_or_dog_resolver(*_args, **_kwargs):
    return {
        "name": "Dogo",
    }
```

### LINKED ISSUE #216: mutation validation error message is not very helpful
## Request a feature

* [ ] **Tartiflette version:** _0.8.8_

When required fields are missing in an input Object (at root or nested), the returned error message reports the field is missing from the mutation result object rather than indicating where in the input it is actually missing

e.g. this error is returned

```json
{
  "data": {
    "createFenixShipment": null
  },
  "errors": [
    {
      "message": "Invalid value (value: None) for field `createFenixShipment` of type `createFenixShipmentResult`",
      "path": [
        "createFenixShipment"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```
when I submit this mutation it would be helpful to get an error about missing `vendorCode` on `createFenixShipment.fenixShipment.CCIs[0]`  or something that at least mentioned `vendorCode` instead of `createFenixShipmentResult` which is an output type.

```graphql
mutation{
  createFenixShipment(input: {
    fenixShipment: {
      importerCode: "test",
      fileNumber: "test",
      ccIs: [
        {
          importerCode: "required",
          vendorCode: null
        }
      ]
    }
  }
  ) {
    status
  }
}
```
Part of the schema def is shown below
```graphql
type Mutation {
    createFenixShipment(input: FenixShipmentInput!): createFenixShipmentResult
}

type createFenixShipmentResult {
    status: String!
    message: String
}

input FenixShipmentInput {
    fenixShipment: FenixShipment!
}

input FenixShipment {
    transactionNumber: String
    fileNumber: String!
    importerCode: String!
    ccIs: [CCI!]
}

input CCI {
    importerCode: String!
    importerAddress: Address
    vendorCode: String!
}
```

### LINKED ISSUE #277: Interface __typename not supported, nested "... on" error
I found 2 different problems with query processing:

1. `__typename` doesn't work on Interfaces
1. `field ... was not found in GraphQL schema` error occurs on the first next field after a nested `... on` statement in the query

**Schema**
```graphql
schema {
    query: RootQuery
}

type RootQuery {
    vehicles: Vehicle
}

type Model {
    name: String
}

interface Vehicle {
    color: Color
}

type Car implements Vehicle {
    color: Color
    model: Model
}

interface Color {
    rgb: String
}

type Blue implements Color {
    rgb: String
}
```

**Query**
```graphql
{
  vehicles
  {
    __typename
    ... on Car {
      color {
        ... on Blue {
          rgb
        }
      }
      model {
        name
      }
    }
  }
}
```

**Errors**
```json
{
  "data": null,
  "errors": [
    {
      "message": "field `Vehicle.__typename` was not found in GraphQL schema.",
      "path": [
        "vehicles",
        "__typename"
      ],
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    },
    {
      "message": "field `Vehicle.model` was not found in GraphQL schema.",
      "path": [
        "vehicles",
        "model"
      ],
      "locations": [
        {
          "line": 11,
          "column": 7
        }
      ]
    }
  ]
}
```

**Tartiflette version:** 0.12.4
**Python version:** 3.7
**Executed in docker:** Yes, but same problem reproducible when executed outside.
**Is it a regression from a previous versions?** No

### LINKED ISSUE #278: `extend type` is ignored
Extended fields are ignored
```graphql
type Query {
    hello: String
}

extend type Query {
    world: String
}
```

The generated graphql schema contains only hello

Schermata 2019-08-24 alle 15 49 34

### LINKED ISSUE #284: GraphiQL JS error with tartiflette 1.0RC1
I've been testing the tartiflette RC1 (https://github.com/tartiflette/tartiflette/pull/272) with tartiflette-aiohttp and noticed that GraphiQL crashes with this error:

```
GraphQLError: Syntax Error: Expected <EOF>, found Name "longer"
    at syntaxError (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:23522:10)
    at expect (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:28513:32)
    at parseValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:27279:3)
    at buildInputValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33676:118)
    at https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25955:31
    at Array.reduce (<anonymous>)
    at keyValMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25954:15)
    at buildInputValueDefMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33669:36)
    at buildDirective (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33696:13)
    at Array.map (<anonymous>)
```

### PR DESCRIPTION
**Pull request by abusi**
> Warn. This is still WIP, but we are nearly there, we hope for a delivery around september. Just to let you know about what's coming next.
> Test version is availble doing :
> ```
> pip install --extra-index-url https://test.pypi.org/simple/ tartiflette==1.0.0rc1.dev1567069372
> ```

# [1.0.0] - Soon (TM)

## Added

- [ISSUE-122](https://github.com/dailymotion/tartiflette/issues/122) - Implementation of a new `@TypeResolver` decorator to allow the resolution of the concrete type of a result linked to an abstract type (union or interface) in a generic way ([more detail here](https://tartiflette.io/docs/api/type-resolver/#@typeresolver))
- [ISSUE-122](https://github.com/dailymotion/tartiflette/issues/122) - Implementation of a new `type_resolver` parameter on the `@Resolver` decorator to allow the resolution of the concrete type of the field result linked to the resolved field abstract type (union or interface) ([more detail here](https://tartiflette.io/docs/api/type-resolver/#@resolver))
- [ISSUE-122](https://github.com/dailymotion/tartiflette/issues/122) - Implementation of a new `custom_default_type_resolver` parameter on the `create_engine` function and the `__init__` and `cook` method of the `Engine` class. This parameter allow to override the default type resolver provided by Tartiflette to resolve the concrete type of abstract type fields ([more detail here](https://tartiflette.io/docs/api/type-resolver/#@overriding-the-default-type-resolver))
- A new `GraphQLInputField` type has been implemented to more clearly distinguish the difference between an argument and an input field and be closer to the GraphQL specification
- The parsing of the same query and its validation is now cached to improve performance when the same query is played regularly

## Changed

- Bump the `libgraphqlparser` submodule to latest master commits so we can now support triple quoted strings as litteral values for parameters.
  **Note**: It's important to have at least `bison` in version >= 3 on your system before installing tartiflette.
- Bump the `lark-parser` package to version `0.7.3`
- [ISSUE-121](https://github.com/dailymotion/tartiflette/issues/121) - The grammar used by the lark parser used in the SDL parsing has been updated to conform to the [June 2018 GraphQL specification](https://graphql.github.io/graphql-spec/June2018/)
- [ISSUE-121](https://github.com/dailymotion/tartiflette/issues/121) - Both SDL and query parsing does now focus only on the parsing part and returns an instance of `DocumentNode` that can be treated generically
- Built-in Tartiflette SDL parts (introspection types, directives, scalars...) have been modified to add descriptions on the various built-in types in order to make the introspection queries more complete
- In order to solve the performance issues related to the execution of introspection requests, we proceeded to a big work of pre-compute of the various fields of introspection at the initialization of the Tartiflette engine in order to answer as quickly as possible to the introspection queries
- In order to improve performance and thus reduce the execution time of queries, the majority of coercion algorithms are now pre-computed for each type, scalar, directive, etc. at engine initialization
- The values of the variables are now computed before executing the requested operation (as specified in the [GraphQL specification](https://graphql.github.io/graphql-spec/June2018/#ExecuteRequest())). This allows us to execute the requested operation only if variables coercion doesn't return any errors.

    **Note**: it is important to note that the computing of values of the variables includes the entire coercion process as well as the execution of potential directives applied on the scalar or input fields of the variable type:
    * directives will only be executed once when calculating the value of each variable and no longer at each occurrence of the variable in the query
    * if a directive returns an error at coercion time of a variable, the whole operation will not be executed, when previously, only the field where the variable is used would have been in error
- [ISSUE-216](https://github.com/dailymotion/tartiflette/issues/216) - An important work on error handling has been done. Error messages are now more explicit and relevant. In addition, the keys `path` and `locations` in error items should now also be more relevant and accurate than before
- The [`error_coercer`](https://tartiflette.io/docs/api/error-handling#advanced-add-a-global-error-coercer) parameter now expects an asynchronous function instead of a synchronous function ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#engine_coercer-has-to-be-asynchronous))
- The shape of the [`info`](https://tartiflette.io/docs/api/resolver#resolver-info-argument) parameter accessible in particular in the resolvers and some hooks of directives has been completely changed ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#the-shape-of-the-info-parameter-has-changed))
- The `@Subscription` decorator no longer has its specific default resolver. This means that the messages returned by `@Subscription` will no longer be wrapped with the field name as before (when the field doesn't have a dedicated `@Resolver`) ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#subscriptions-no-longer-have-a-specific-default-resolver))
- We now make a strong distinction between non-supplied values and `null` values. This is to avoid passing the `null` value when a value has not been supplied (especially for arguments) ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#strong-distinction-between-non-supplied-values-and-null-values))
- The signature of the following directives hook methods has been changed to `on_argument_execution`, `on_post_input_coercion` and `on_pre_output_coercion` ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#directives))
- Scalar definition now requires the implementation of a third `parse_literal` method ([see the migration guide for more information](https://github.com/tartiflette/tartiflette/blob/ISSUE-121-document-node-execution/docs/migration-guides/0.x.x-to-1.x.x.md/#scalar-definitions) or [documentation on scalar](https://tartiflette.io/docs/api/scalar))

## Fixed

- The type of the `__Type.kind` field has been fixed for `__TypeKind!` instead of `__TypeKind` in the built-in introspection SDL
- The optional argument `includeDeprecated` defined on the `__Type.enumValues` and `__Type.fields` introspection fields is now functional and allows to filter the result respectively to the deprecations of enum values or fields
- The directives applied to input fields are now calling the `on_post_input_coercion` directive hook instead of `on_argument_execution`
- The coercion of the arguments is fully functional and the directives applied to the arguments of another directives are now well triggered and computed
- In some specific and complex cases, the `@if` and `@skip` built-in directives could behave unexpectedly and undesirably, their behaviour has been fixed
- [ISSUE-277](https://github.com/dailymotion/tartiflette/issues/277) - Abstract types are better handled especially the interfaces that are now executed and resolved correctly when using fragment and the `__typename` field

# Related issues
* Closes #121 
* Closes #122
* Closes #216  
* Closes #277
* Closes #284
* Closes #278

### CODE REVIEW

**Comment by aljinovic** [comment]
Hello, any news about the  https://test.pypi.org release?

**Comment by abusi** [comment]
Hi @aljinovic, it should come sometime during next week.

**Comment by abusi** [comment]
This will also fix #277

**Comment by abusi** [comment]
> Hello, any news about the https://test.pypi.org release?

@aljinovic You can try using `pip install -i https://test.pypi.org tartiflette==0.12.4a1566896886` if you wanna give it a spin.

**Comment by aljinovic** [comment]
> pip install -i https://test.pypi.org tartiflette==0.12.4a1566896886

It's actually: `pip install -i https://test.pypi.org/simple tartiflette==0.12.4a1566896886` if someone else also needs it.

**Pull request merged**
