### PR TITLE
ISSUE-457 - Improve performance for I/O bound list resolvers by using parallel execution

### LINKED ISSUE #457: Improve performance for I/O bound list resolvers by using parallel execution
At the moment, when an output list contains objects that themselves have an I/O bound resolver (eg. a secondary network RPC call to add more fields to the list items), then the list item resolvers are executed sequentially (see [discussion yesterday](https://github.com/tartiflette/tartiflette/pull/456), and also the [original PR](https://github.com/tartiflette/tartiflette/pull/367) that introduced sequential resolution).

The concern here is that the elapsed wall-clock time to resolve the entire query is unnecessarily slow, because we have to wait for a sequence of network calls, which could potentially be executed in parallel instead. I'd like to start a discussion about how we could restore parallel execution for this scenario, whilst still addressing the concerns that led us to use sequential execution.

I am not fully aware of the issues. I am guessing they include:

1. Reduce the overhead of an asyncio task for trivial resolvers
1. Reduce the overhead of an asyncio task for non-output coercion
1. Reduce the cost of starting an asyncio task for every member of a lengthy list

As a conversation starter, here are some ideas for the type of behaviour we might want (either standalone, or potentially combined) to address the I/O bound list resolver scenario outlined above:

1. Only apply this functionality to the list_coercer for outputs (since they are most likely to involve I/O)
1. Create asyncio tasks in chunks (eg. maximum 10 at a time)
1. Only create asyncio tasks if there is at least 1 resolver (I don't think I am expressing this correctly - I mean if there is a `@resolver`-decorated async python function that needs to be executed in order to get the output value for a requested field)
1. Provide a hook on the resolver for the field that produces the list, allowing it to specify an alternate list_coercer
1. Provide a hook on the engine, allowing developers to specify a custom list_coercer
1. Or something else... ;-)

Can you please comment? Thanks

### PR DESCRIPTION
**Pull request by Maximilien-R**
Closes #457.

### CODE REVIEW

**Comment by abusi** [comment]
Seems really cool @Maximilien-R

**Comment by Maximilien-R** [comment]
Hi @abusi & @garyd203,

Following our discussions on the #457 issue, here is a first draft aiming to fix it.

Currently, I do fix only the list output coercion aspect. On the issue thread, I suggested to do something similar for output object coercion however this topic will be less straight forward. Indeed, there is the case for abstract object (Union & Interface) that should be discuss before going forward. Also, since on `tartiflette` we do build all the coercer function at engine baking its harder to manipulate the object/abstract coercion.

I think we could go on the object/abstract coercion customization on another PR. What I would like to do it to be able to really fine tuning it per object field instead of the parent field like its done for list.

For instance, if we had the following SDL:
```graphql
type Author {
  id: ID!
  firstName: String!
  lastName: String!
  birthdate: Date!
}

type Book {
  id: ID!
  title: String!
  authors: [Author!]
  nbPages: Int!
  resume: String!
  opinions: [String!]
}

type Query {
  books: [Book!]
}
```

We could imagine that the `Query.books` resolver will be able to return must of the data necessary to resolve each `Book` but we could need for the `Book.authors` & `Book.opinions` fields to have a dedicated resolver in order to fetch the data on another data source.

As it's designed currently, we'll `asyncio.gather` all the `Book` fields either it call the default resolver or a dedicated one. What I could like to do (test) is that we could define which field should be `asyncio.gather` (those which do I/O) and which field should be coerce sequentially.

We could have something like:
```python
@Resolver("Query.books")
async def resolve_query_books(parent, args, ctx, info):
  return Books.objects.all()


@Resolver("Book.authors", concurrently=True)
async def resolve_book_authors(parent, args, ctx, info):
  return Authors.objects.filter(pk__in=parent["authors"]).all()


@Resolver("Book.opinions", concurrently=True)
async def resolve_book_authors(parent, args, ctx, info):
  return Opinions.objects.filter(book_id=parent["id"]).all()
```

The difference with the list is that its the field resolver which will impact the parent resolving process.

Tell me if I'm not clear 😆

**Comment by abusi** [comment]
I agree that it should be discussed in another PR, we'll keep this one for List only so it's clearer :)

**Comment by garyd203** [comment]
Looks good @Maximilien-R  thank you very much

I understand what you are saying about only doing concurrent resolution if there is a field that needs I/O (ie. the field has a non-dumb resolver), and agree. I suspect that applies to the list case too, not just objects - a list only really needs a concurrent resolver because one or more of the fields on each item needs concurrent resolution. So it seems broadly similar, just 1 step further removed (list_field -> item_in_list_field -> field_on_item_with_non_default_resolver)

**Comment by abusi** [comment]
@Maximilien-R shall we merge ?

**Comment by Maximilien-R** [comment]
@abusi, I guess we could if it's fine for you 👍

**Review by abusi — APPROVED** [review]

**Pull request merged**
